### ISSUE TITLE
Add Cryptocurrency Coins

### ISSUE THREAD

**Issue by trymeouteh** [airgap-it/airgap-vault#41] opened 2021-02-16 17:50 UTC
I will create this issue which people can add what coins they want supported in AirGap. I would also like to have anyone who wants a coin added to AirGap look at my Plugin purposal which can be a way to allow coins to be added to AirGap without having the AirGap devs having to maintain all of these coins.

Plugin Purposal
https://github.com/airgap-it/airgap-vault/issues/40

Please search this issue for the coin you want to see before creating a post to have it added and if you want the coin, thumbs up the post. To add a coin to this issue, add the coin name and the ticker symbol.

**Comment by trymeouteh** [comment] 2021-02-16 17:51
Bitcoin Cash - BCH

**Comment by trymeouteh** [comment] 2021-02-16 17:51
Litecoin - LTC

**Comment by trymeouteh** [comment] 2021-02-16 17:51
Dash - DASH

**Comment by trymeouteh** [comment] 2021-02-16 17:51
Monero - XMR

**Comment by trymeouteh** [comment] 2021-02-16 17:52
Digibyte - DGB

**Comment by trymeouteh** [comment] 2021-02-16 17:52
Firo - Firo

**Comment by trymeouteh** [comment] 2021-02-16 17:52
NIX - NIX (Will soon be an ERC20 token)

https://github.com/airgap-it/airgap-vault/issues/38

**Comment by trymeouteh** [comment] 2021-02-16 21:22
Unstoppable Domains

I made an issue on how the wallet could integrate these assets
https://github.com/airgap-it/airgap-vault/issues/37

**Comment by trymeouteh** [comment] 2021-02-16 21:23
Zilliqa - ZIL (For Unstoppable Domain .zil domain support)

I made an issue on how the wallet could integrate these assets
#37

**Comment by trymeouteh** [comment] 2021-02-22 22:32
ERC20 Tokens

Please allow users to add any ERC20 Token and naming the ERC20 contact in the wallet for reference. This way all ERC20 tokens will be supported in AirGap and AirGap devs can add certain ERC20 Tokens as they do now.

**Comment by AndreasGassmann** [comment] 2021-03-02 16:53
Regarding ERC-20 tokens, we are currently working on WalletConnect support, which will allow users to use all ERC-20 tokens through a tool like MEW.

For other tokens, we are always looking forward to working with projects to add new coins to AirGap. But due to the effort required (implementation, testing, 3rd party audit), we usually work together with an entity behind that project. So if you know anyone inside those projects, let us know (or let them know we would be interested).

**Comment by trymeouteh** [comment] 2021-03-09 03:05
I understand maintaining coins in a wallet take time. That is why the plugin like system may make it easier to maintain if you can brand Airgap in a way that Ledger and Trezor branded their wallets were crypto devs add support for their coin. I will try to inform these crypto projects about Airgap as the secure fully open source wallet.

https://github.com/airgap-it/airgap-vault/issues/40

**Comment by maxfrei750** [comment] 2021-04-23 15:30
Cardano - ADA

**Comment by ajboni** [comment] 2021-04-27 04:00
Algorand - ALGO

**Comment by mdecerbo** [comment] 2021-05-13 08:00
> Cardano - ADA

:+1:

**Comment by Kippenhof** [comment] 2021-12-29 15:41
> Monero - XMR

Is there some Progress on Implementing Monero/XMR? It would be nice if i could store all my Coins in one Wallet.

**Comment by AndreasGassmann** [comment] 2021-12-29 16:38
> Is there some Progress on Implementing Monero/XMR? It would be nice if i could store all my Coins in one Wallet.

We are not actively working on Monero/XMR support. However, with the upcoming upgrade of the Monero network, managing air-gapped wallets could get easier. So we're staying tuned for that.

But as with other coins, the main issue is time and funding. Adding a new coin is a huge commitment, and especially a coin like Monero will require more changes than normal protocols (because not everything is public, things need to be decrypted, etc). But it would be great fit for our wallet.

**Comment by mdecerbo** [comment] 2022-03-15 19:45
Please consider implementing support for [ZEC](https://github.com/zcash/), although rather than deal with the addressing mess it has now, you would probably want to wait until it has implemented [unified addressing](https://electriccoin.co/blog/unified-addresses-in-zcash-explained/).

ZEC is great technology and there are [grants available](https://zcashcommunitygrants.org/) for which this kind of work is explicitly in scope.

**Comment by audiophilesvv** [comment] 2022-07-02 14:56
Trx and the trc20 tokens

**Comment by alfredonodo** [comment] 2022-11-28 15:16
Hi,
this project is very interesting as it is open source, with reproducible builds, audit (although not up-to-date) and multi-platform. Please add at least the [first 30 coins](https://cryptpad.fr/sheet/#/3/sheet/view/cedebcdbda258f00a98154c7f1eef3f8/) on CoinMarketCap.
Thank you

**Comment by martin-braun** [comment] 2023-03-27 22:10
@AndreasGassmann AirGap really peaked my interest today, but without XMR this is hard to consider as main wallet. Monero is de-facto the most private mainstream-ish coin. Is there an update about the progress?

**Comment by debeldami** [comment] 2023-12-19 11:34
We now support a plugin system called [isolated module](https://support.airgap.it/isolated-module), with this new feature, you can add any blockchain of your choice to AirGap. I'll be closing this issue now. If you have any additional questions, please don't hesitate to reopen. Your feedbacks are appreciated. Thank you!

**Closed by debeldami** 2023-12-19 11:34 UTC
