### ISSUE TITLE
Issue Signing on Optimism

### ISSUE THREAD

**Issue by pvdyck** [airgap-it/airgap-vault#199] opened 2023-08-04 06:16 UTC
Signing this optimism transaction hangs just after the scan.
Nothing happens ...
<img width="367" alt="Capture d’écran 2023-08-04 à 08 15 19" src="https://github.com/airgap-it/airgap-vault/assets/460696/438ff554-e102-4728-9ecf-b53db534402b">

**Comment by AndreasGassmann** [comment] 2023-08-05 07:31
Hi. Could you let us know which version of the Vault you are using? Earlier versions of the Vault used to have problems with Optimism, but that should be fixed in the latest version.

**Comment by pvdyck** [comment] 2023-08-07 14:22
Latest

**Comment by pvdyck** [comment] 2023-08-08 08:10
Were you able to reproduce ? It's a transaction exiting a beefy vault => https://app.beefy.finance/vault/velodrome-lusd-dai

**Comment by pvdyck** [comment] 2023-08-11 09:23
@airgap-gitlab any help here ?

**Comment by pvdyck** [comment] 2023-08-11 09:25
@airgap-it any help here ?

**Comment by pvdyck** [comment] 2023-08-14 14:57
Issue still there with latest release
please HELP !

**Comment by mlaeng** [comment] 2023-08-15 14:44
Hey @pvdyck I am sorry we couln't help yet. Can you tell us the exact setup you're using? I can't identify where the screenshot you posted is coming from. Is that Metamask + Airgap Vault?

**Comment by pvdyck** [comment] 2023-08-15 14:49
Yes exactly

**Comment by pvdyck** [comment] 2023-08-15 14:51
Rabby chrome extension, how can I help you better to find out the exact issue? Thanks

**Comment by mlaeng** [comment] 2023-08-15 15:11
@pvdyck In the meantime I was able to find out what your setup is. I got the Rabby extension and did setup one of my Optimism accounts from my Airgap vault to use. I was able to deposit in this vault: 

https://app.beefy.finance/vault/velodrome-v2-op-velo

And could easily sign using AirGap vault. I am using 3.29.0 (build 53670) on Android.

**Comment by pvdyck** [comment] 2023-08-15 15:22
Android - Sony , all software updates installed (including the webview) / Airplane mode / Not using any other app on the phone
Using Moto e7(i) Power / Android 10 
Airgap-Vault latest version

**Comment by mlaeng** [comment] 2023-08-15 15:23
@pvdyck does it look like this after scanning the Qr code?

![image](https://github.com/airgap-it/airgap-vault/assets/1638365/6ab49d5f-645d-459a-8914-6f4993b6199b)

**Comment by pvdyck** [comment] 2023-08-15 15:25
yes, exactly, black screen !

**Comment by mlaeng** [comment] 2023-08-15 15:27
Well, not completely black... Bizarre. I got the same when I scanned the QR code which you posted above. But If I scanned the Qr code that was displayed for me it worked without a problem... It is also the case that now I need to exit the AirGap Vault completely in order to get the camera again. I need to check something.

**Comment by pvdyck** [comment] 2023-08-15 15:30
Great, as long as you can reproduce it ... The problem is half solved 😉

**Comment by mlaeng** [comment] 2023-08-15 15:31
Do you have more than one account synced with Rabby?

**Comment by mlaeng** [comment] 2023-08-16 07:03
@pvdyck pls let me know if that was the issue or if we have to look further...

**Comment by pvdyck** [comment] 2023-08-16 07:08
I'll check in a couple of hours and get back to you, thanks for the great support

**Comment by mlaeng** [comment] 2023-08-16 10:37
@pvdyck it shouldn't be Optimism related, because Optimism interactions work just fine with my setup, which is pretty similar to yours. But I want to check something else as soon as I find time, thanks for your patience.

**Comment by mlaeng** [comment] 2023-08-16 10:58
@pvdyck a thought I just had. Did you already try to remove the wallet from rabby and then connect it again?

**Comment by pvdyck** [comment] 2023-08-16 11:02
No, will do and keep you posted.
It's displayed properly in Rabby, the derivation path is correct.

**Comment by mlaeng** [comment] 2023-08-16 11:05
is it another derivation index than 0?

**Comment by pvdyck** [comment] 2023-08-16 15:21
Uninstalled/reinstalled Rabby / Reinstalled airgap vault's wallet - problem persists 
Same derivation index ( 0 )

**Comment by pvdyck** [comment] 2023-08-16 15:25
Successfully signed transactions on Fantom, Avalanche, Polygon and BSC
Only fails on Optimism

**Comment by bserrao** [comment] 2023-10-17 13:33
I've having a similar issue when trying to sign a ETH transaction to another account. When it reads the QR code the screen goes black like the screenshot above a nothing happens.
Now i'm stuck and unable to make the transaction.

**Comment by debeldami** [comment] 2023-12-19 13:28
Hi @pvdyck 

To successfully sign transactions on Optimism, you have to add Optimism to your Vault. Failure to do so will result in a black screen during the signing process. I've verified and reproduced this issue, and it consistently occurs when Optimism is not added to the Vault. Please make sure to include Optimism in your Vault to avoid encountering this problem. I will now close the issue.

**Closed by debeldami** 2023-12-19 13:28 UTC

**Comment by pvdyck** [comment] 2023-12-20 07:52
Thanks ! It might be useful to catch this and display an informative message.

**Comment by peterwilli** [comment] 2024-05-26 11:41
> Hi @pvdyck
> 
> To successfully sign transactions on Optimism, you have to add Optimism to your Vault. Failure to do so will result in a black screen during the signing process. I've verified and reproduced this issue, and it consistently occurs when Optimism is not added to the Vault. Please make sure to include Optimism in your Vault to avoid encountering this problem. I will now close the issue.

Thanks that solved it for me! It would be a good idea to actually mention this somewhere, this kept me up for hours!
